// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalExpertSchedule
{
    public int ScheduleId { get; set; }

    public int? ExpertId { get; set; }

    public string DayOfWeek { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? IsActive { get; set; }
    [JsonIgnore]
    public virtual MedicalExpert Expert { get; set; }
}