// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalHistory
{
    public int HistoryId { get; set; }

    public int? AppointmentId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public bool? Payed { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    [JsonIgnore]
    public virtual Appointment Appointment { get; set; }
    [JsonIgnore]
    public virtual ICollection<HealthRecord> HealthRecords { get; set; } = new List<HealthRecord>();
    [JsonIgnore]
    public virtual RatingsAndFeedback RatingsAndFeedback { get; set; }
}