// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MedicaiFacility.BusinessObject;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int? PatientId { get; set; }

    public int? ExpertId { get; set; }

    public int? FacilityId { get; set; }

    public string Note { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public int? TransactionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    [JsonIgnore]
    public virtual MedicalExpert Expert { get; set; }
    [JsonIgnore]
    public virtual MedicalFacility Facility { get; set; }
    [JsonIgnore]
    public virtual MedicalHistory MedicalHistory { get; set; }
    [JsonIgnore]
    public virtual Patient Patient { get; set; }
    [JsonIgnore]
    public virtual Transaction Transaction { get; set; }
}